# Generated by Django 5.2.5 on 2025-09-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('button1_text', models.CharField(max_length=255)),
                ('button1_link', models.URLField()),
                ('button2_text', models.CharField(max_length=255)),
                ('button2_link', models.URLField()),
                ('image', models.ImageField(upload_to='static/hero_images/')),
            ],
        ),
    ]
