# Generated by Django 5.2.5 on 2025-09-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider1_title', models.CharField(max_length=255)),
                ('slider1_subtitle', models.TextField()),
                ('slider2_title', models.CharField(max_length=255)),
                ('slider2_subtitle', models.TextField()),
                ('slider3_title', models.CharField(max_length=255)),
                ('slider3_subtitle', models.TextField()),
                ('image', models.ImageField(upload_to='static/banner_images/')),
            ],
        ),
    ]
