# Generated by Django 5.2.5 on 2025-09-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_bannermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannermodel',
            name='image',
        ),
    ]
