# Generated by Django 5.2.5 on 2025-09-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_bannermodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_title', models.CharField(max_length=255)),
                ('services_description', models.TextField()),
                ('services_feature1', models.CharField(max_length=255)),
                ('services_feature2', models.CharField(max_length=255)),
                ('services_feature3', models.CharField(max_length=255)),
                ('services_feature4', models.CharField(max_length=255)),
                ('services_button_text', models.CharField(max_length=255)),
                ('services_button_link', models.URLField()),
                ('services_logo', models.ImageField(upload_to='static/services_images/')),
            ],
        ),
    ]
