# Generated by Django 5.2.5 on 2025-09-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_servicesmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesmodel',
            name='services_logo',
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='services_check_icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
