# Generated by Django 5.2.5 on 2025-09-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_servicesmodel_services_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmodel',
            name='servisec_logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
