# Generated by Django 5.2.5 on 2025-09-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_servicesmodel_servisec_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_title', models.CharField(max_length=255)),
                ('technology_description', models.TextField()),
                ('technology_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('technology_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='servicesmodel',
            old_name='servisec_logo',
            new_name='services_logo',
        ),
    ]
