# Generated by Django 5.2.5 on 2025-09-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_technologymodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmodel',
            name='services_hidding',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='services_sub_hidding',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
