# Generated by Django 5.2.5 on 2025-09-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_servicesmodel_services_hidding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(blank=True, max_length=255)),
                ('section_subtitle', models.TextField(blank=True)),
                ('case_title', models.CharField(max_length=255)),
                ('case_tag', models.CharField(max_length=255)),
                ('case_image', models.ImageField(upload_to='static/case_study_images/')),
                ('case_problem_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('case_problem_text', models.TextField()),
                ('case_solution_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('case_solution_text', models.TextField()),
                ('case_result_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('case_result_text', models.TextField()),
                ('case_technologies', models.CharField(max_length=255)),
                ('case_button_text', models.CharField(max_length=255)),
                ('case_button_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CTAModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('section_subtitle', models.TextField()),
                ('cta_button_text', models.CharField(max_length=255)),
                ('cta_button_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='IndustriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(blank=True, max_length=255)),
                ('section_subtitle', models.CharField(blank=True, max_length=255)),
                ('industries_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('industries_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(blank=True, max_length=255)),
                ('section_subtitle', models.TextField(blank=True)),
                ('partner_logo', models.ImageField(upload_to='static/partner_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(blank=True, max_length=255)),
                ('section_subtitle', models.TextField(blank=True)),
                ('client_content', models.TextField()),
                ('author_name', models.CharField(max_length=255)),
                ('author_position', models.CharField(max_length=255)),
                ('author_image', models.ImageField(upload_to='static/testimonial_images/')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('section_subtitle', models.TextField()),
                ('choose_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('choose_name', models.CharField(max_length=255)),
                ('choose_description', models.TextField()),
            ],
        ),
    ]
