# Generated by Django 5.2.5 on 2025-09-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_casestudymodel_ctamodel_industriesmodel_partnermodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctamodel',
            name='section_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ctamodel',
            name='section_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='whychooseusmodel',
            name='section_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='whychooseusmodel',
            name='section_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
