# Generated by Django 5.2.5 on 2025-09-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_ctamodel_section_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnermodel',
            name='section_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
