# Generated by Django 5.2.5 on 2025-09-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_partnermodel_section_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologymodel',
            name='technology_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
