# Generated by Django 5.2.5 on 2025-09-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_technologymodel_technology_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologymodel',
            name='technology_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='technologymodel',
            name='technology_icon',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='technologymodel',
            name='technology_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
