# Generated by Django 5.2.5 on 2025-09-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_technologymodel_technology_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologymodel',
            name='technology_description',
        ),
        migrations.RemoveField(
            model_name='technologymodel',
            name='technology_title',
        ),
    ]
