# Generated by Django 5.2.5 on 2025-09-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_technologymodel_technology_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industriesmodel',
            name='section_subtitle',
        ),
        migrations.RemoveField(
            model_name='industriesmodel',
            name='section_title',
        ),
    ]
