# Generated by Django 5.2.5 on 2025-09-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_remove_industriesmodel_section_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudymodel',
            name='section_subtitle',
        ),
        migrations.RemoveField(
            model_name='casestudymodel',
            name='section_title',
        ),
        migrations.RemoveField(
            model_name='ctamodel',
            name='section_subtitle',
        ),
        migrations.RemoveField(
            model_name='ctamodel',
            name='section_title',
        ),
        migrations.RemoveField(
            model_name='partnermodel',
            name='section_subtitle',
        ),
        migrations.RemoveField(
            model_name='partnermodel',
            name='section_title',
        ),
        migrations.RemoveField(
            model_name='testimonialsmodel',
            name='section_subtitle',
        ),
        migrations.RemoveField(
            model_name='testimonialsmodel',
            name='section_title',
        ),
        migrations.RemoveField(
            model_name='whychooseusmodel',
            name='section_subtitle',
        ),
        migrations.RemoveField(
            model_name='whychooseusmodel',
            name='section_title',
        ),
    ]
