# Generated by Django 5.2.5 on 2025-09-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_remove_casestudymodel_section_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_title', models.CharField(max_length=255)),
                ('mission_description', models.TextField()),
                ('mission_icon', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurJourneyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeline_date', models.CharField(max_length=255)),
                ('timeline_title', models.CharField(max_length=255)),
                ('timeline_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VisionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_title', models.CharField(max_length=255)),
                ('vision_description', models.TextField()),
                ('vision_icon', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
