# Generated by Django 5.2.5 on 2025-09-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_missionmodel_ourjourneymodel_visionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementsAwardsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_icon', models.CharField(blank=True, max_length=100, null=True)),
                ('achievement_title', models.CharField(max_length=200)),
                ('award_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CertificationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_image', models.ImageField(blank=True, null=True, upload_to='static/certifications/')),
                ('company_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_image', models.ImageField(blank=True, null=True, upload_to='static/team_images/')),
                ('member_name', models.CharField(max_length=100)),
                ('member_position', models.CharField(max_length=100)),
                ('member_expert', models.TextField(blank=True, null=True)),
                ('member_linkedin_url', models.URLField(blank=True, max_length=255, null=True)),
                ('member_linkedin_icon', models.CharField(blank=True, max_length=100, null=True)),
                ('member_twitter_url', models.URLField(blank=True, max_length=255, null=True)),
                ('member_twitter_icon', models.CharField(blank=True, max_length=100, null=True)),
                ('member_envelope_url', models.EmailField(blank=True, max_length=255, null=True)),
                ('member_envelope_icon', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValuesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_icon', models.CharField(blank=True, max_length=100, null=True)),
                ('value_title', models.CharField(max_length=200)),
                ('value_description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='ctamodel',
            name='cta_button_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ctamodel',
            name='cta_button_url',
            field=models.URLField(max_length=255),
        ),
    ]
