# Generated by Django 5.2.5 on 2025-09-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_achievementsawardsmodel_certificationsmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCTAModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cta_button_text', models.CharField(max_length=100)),
                ('cta_button_url', models.URLField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='ctamodel',
            name='cta_button_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ctamodel',
            name='cta_button_url',
            field=models.URLField(),
        ),
    ]
